<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<PackageId>ModernFormsNext.Templates</PackageId>
		<Version>1.0.0</Version>
		<Title>ModernFormsNext Templates</Title>
		<Authors>ProGraMajster</Authors>
		<Company>ProGraMajster</Company>
		<Description>Project templates for ModernFormsNext.</Description>
		<PackageTags>ModernFormsNext;Templates;dotnet-new;CSharp;Desktop;UI;Windows</PackageTags>
		<PackageType>Template</PackageType>
		<IncludeContentInPack>true</IncludeContentInPack>
		<IncludeBuildOutput>false</IncludeBuildOutput>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/ProGraMajster/ModernFormsNext</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ProGraMajster/ModernFormsNext</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		
		<NoWarn>$(NoWarn);NU5128</NoWarn>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="templates\**\*" Pack="true" PackagePath="content" />
		<Compile Remove="templates\modernformsnext-app\MainForm.cs" />
		<Compile Remove="templates\modernformsnext-app\Program.cs" />
		<Content Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>