namespace ModernFormsNext.CodeGeneration.Reverse;

/// <summary>
/// Provides small executable examples for the conservative C# designer parser.
/// </summary>
/// <remarks>
/// These examples intentionally mirror the deterministic shape emitted by
/// <see cref="CSharp.CSharpDesignerGenerator"/>. They are useful for smoke testing in
/// hosts without introducing a full test project.
/// </remarks>
public static class CSharpDesignerParserExamples
{
    /// <summary>
    /// Creates a sample designer file with one button directly on the form.
    /// </summary>
    /// <returns>Example C# designer source.</returns>
    public static string CreateSimpleButtonSource()
        => """
           // <auto-generated />

           using ModernFormsNext;

           namespace MyApp;

           public partial class MainForm
           {
               private Button button1 = null!;

               private void InitializeComponent()
               {
                   this.button1 = new Button();

                   this.button1.Name = "button1";
                   this.button1.Text = "OK";
                   this.button1.Bounds = new System.Drawing.Rectangle(20, 40, 100, 30);
                   this.button1.Dock = ModernDockStyle.Top;
                   this.button1.Click += this.button1_Click;

                   this.Controls.Add(this.button1);

                   this.Name = "MainForm";
                   this.Text = "MainForm";
                   this.Size = new System.Drawing.Size(900, 600);
               }
           }
           """;

    /// <summary>
    /// Creates a sample designer file with a panel containing a label and button.
    /// </summary>
    /// <returns>Example C# designer source.</returns>
    public static string CreateNestedPanelSource()
        => """
           // <auto-generated />

           using ModernFormsNext;

           namespace MyApp;

           public partial class MainForm
           {
               private Panel panel1 = null!;
               private Label label1 = null!;
               private Button button1 = null!;

               private void InitializeComponent()
               {
                   this.panel1 = new Panel();
                   this.label1 = new Label();
                   this.button1 = new Button();

                   this.panel1.Name = "panel1";
                   this.panel1.Bounds = new System.Drawing.Rectangle(100, 100, 200, 120);

                   this.label1.Name = "label1";
                   this.label1.Text = "Label";
                   this.label1.Bounds = new System.Drawing.Rectangle(20, 20, 80, 24);

                   this.button1.Name = "button1";
                   this.button1.Text = "OK";
                   this.button1.Bounds = new System.Drawing.Rectangle(20, 60, 90, 28);
                   this.button1.Enabled = true;
                   this.button1.Visible = true;

                   this.panel1.Controls.Add(this.label1);
                   this.panel1.Controls.Add(this.button1);
                   this.Controls.Add(this.panel1);

                   this.Name = "MainForm";
                   this.Text = "MainForm";
                   this.Size = new System.Drawing.Size(900, 600);
               }
           }
           """;

    /// <summary>
    /// Parses the nested panel example.
    /// </summary>
    /// <returns>A parser result that should contain a panel with two child controls.</returns>
    public static CSharpDesignerParseResult ParseNestedPanelExample()
        => new CSharpDesignerParser().Parse(CreateNestedPanelSource());
}
