using ModernFormsNext;

namespace MyApp;

/// <summary>
/// Main window generated by the ModernFormsNext project template.
/// </summary>
/// <remarks>
/// This form contains minimal starter content. More advanced control examples are available
/// in the ModernFormsNext ControlGallery sample.
/// </remarks>
public sealed partial class MainForm : ModernFormsNext.Form
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MainForm"/> class.
    /// </summary>
    public MainForm()
    {
        InitializeComponent();
    }

    private void button1_Click(object? sender, EventArgs e)
    {
        Text = "Button clicked";
    }
}
