<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<RootNamespace>MyApp</RootNamespace>
		<AssemblyName>MyApp</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ModernFormsNext" Version="1.8.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="MainForm.cs">
			<ModernFormsNextDesigner>true</ModernFormsNextDesigner>
			<SubType>ModernFormsNextForm</SubType>
		</Compile>
		<Compile Update="MainForm.Designer.cs">
			<DependentUpon>MainForm.cs</DependentUpon>
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
		</Compile>
		<None Update="MainForm.mfdesign">
			<DependentUpon>MainForm.cs</DependentUpon>
		</None>
	</ItemGroup>

</Project>
