using System.Text;
using ModernFormsNext.CodeGeneration.Utilities;
using ModernFormsNext.Designing;

namespace ModernFormsNext.CodeGeneration.CSharp;

/// <summary>
/// Generates ModernFormsNext C# designer partial classes from neutral design documents.
/// </summary>
/// <remarks>
/// The generator emits WinForms-like initialization code while using the actual
/// ModernFormsNext runtime API available today: <c>Bounds</c>, <c>Controls</c>,
/// <c>Dock</c>, <c>Name</c>, <c>Text</c>, and <c>Size</c>. It emits an explicit
/// <c>DockStyle.None</c> when the design document has no dock value so runtime
/// constructor defaults on specialized controls do not change designer-authored
/// layout. It does not depend on Visual Studio SDK services and is deterministic
/// for a given document and option set.
/// </remarks>
public sealed class CSharpDesignerGenerator
{
    private const string DockPropertyName = "Dock";

    private static readonly HashSet<string> GeneratedControlProperties = new(StringComparer.Ordinal)
    {
        "Bounds",
        "Name"
    };

    private static readonly HashSet<string> DesignerOnlyProperties = new(StringComparer.Ordinal)
    {
        DesignNodeRoleNames.RolePropertyName,
        DesignNodeRoleNames.DisplayNamePropertyName,
        DesignNodeRoleNames.DisplayTypePropertyName,
        "TableColumn",
        "TableRow",
        "TableColumnSpan",
        "TableRowSpan"
    };

    private static readonly HashSet<string> GeneratedFormProperties = new(StringComparer.Ordinal)
    {
        "Name",
        "Text",
        "Size"
    };

    /// <summary>
    /// Generates C# designer code for a document.
    /// </summary>
    /// <param name="document">The designer document to generate from.</param>
    /// <param name="options">Optional generation settings.</param>
    /// <returns>The generation result with code and validation messages.</returns>
    public CSharpDesignerGenerationResult Generate(
        DesignDocument document,
        CSharpDesignerGenerationOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(document);

        options ??= new CSharpDesignerGenerationOptions();

        var validation = new DesignDocumentValidator().Validate(document);
        var namespaceName = options.NamespaceOverride ?? document.Namespace;
        var className = options.ClassNameOverride ?? document.ClassName;

        ValidateEffectiveNames(namespaceName, className, validation);
        ValidatePropertyNames(document.Properties.Keys, "form", validation);
        ValidatePropertyNames(document.Controls, validation);

        if (!validation.IsValid)
            return new CSharpDesignerGenerationResult(string.Empty, validation);

        var builder = new StringBuilder();
        var writer = new CodeWriter(builder, options.NewLine);
        var controls = FlattenControls(document.Controls).ToArray();
        var controlExpressions = controls.ToDictionary(
            control => control,
            control => control.MemberVisibility == DesignerMemberVisibility.None ? control.Name : $"this.{control.Name}");

        if (options.EmitAutoGeneratedHeader)
        {
            writer.WriteLine("// <auto-generated />");
        }

        if (options.EmitDesignerMetadataHeader)
        {
            writer.WriteLine("// ModernFormsNext designer file.");

            if (!string.IsNullOrWhiteSpace(options.SourceFilePath))
                writer.WriteLine($"// Source: {options.SourceFilePath}");

            if (!string.IsNullOrWhiteSpace(options.DesignHash))
                writer.WriteLine($"// DesignHash: {options.DesignHash}");
        }

        if (options.EmitAutoGeneratedHeader || options.EmitDesignerMetadataHeader)
            writer.WriteLine();

        writer.WriteLine("using ModernFormsNext;");
        writer.WriteLine();

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            writer.WriteLine($"namespace {namespaceName};");
            writer.WriteLine();
        }

        writer.WriteLine($"public partial class {className}");
        writer.WriteLine("{");

        foreach (var control in controls.Where(control => control.MemberVisibility != DesignerMemberVisibility.None))
        {
            var modifier = CSharpMemberVisibilityWriter.WriteFieldModifier(control.MemberVisibility);
            writer.WriteLine($"    {modifier} {control.TypeName} {control.Name} = null!;");
        }

        if (controls.Length > 0)
            writer.WriteLine();

        writer.WriteLine("    private void InitializeComponent()");
        writer.WriteLine("    {");

        foreach (var control in controls)
        {
            if (control.MemberVisibility == DesignerMemberVisibility.None)
                writer.WriteLine($"        var {control.Name} = new {control.TypeName}();");
            else
                writer.WriteLine($"        this.{control.Name} = new {control.TypeName}();");
        }

        if (controls.Length > 0)
            writer.WriteLine();

        foreach (var control in controls)
            WriteControlInitialization(writer, control, controlExpressions[control], validation);

        foreach (var control in controls)
            WriteControlEvents(writer, control, controlExpressions[control]);

        WriteControlAdds(writer, document.Controls, "this", parentNode: null, controlExpressions);

        if (controls.Length > 0)
            writer.WriteLine();

        var formName = string.IsNullOrWhiteSpace(document.FormName) ? className : document.FormName;
        writer.WriteLine($"        this.Name = {CSharpLiteralWriter.WriteStringLiteral(formName)};");
        writer.WriteLine($"        this.Text = {CSharpLiteralWriter.WriteStringLiteral(formName)};");
        writer.WriteLine($"        this.Size = new System.Drawing.Size({document.Size.Width}, {document.Size.Height});");

        foreach (var property in document.Properties)
        {
            if (GeneratedFormProperties.Contains(property.Key))
                continue;

            WritePropertyAssignment(writer, "this", property.Key, property.Value, "form", validation);
        }

        foreach (var eventBinding in document.Events)
        {
            if (string.IsNullOrWhiteSpace(eventBinding.Value))
                continue;

            writer.WriteLine($"        this.{eventBinding.Key} += this.{eventBinding.Value};");
        }

        writer.WriteLine("    }");
        writer.WriteLine("}");

        return new CSharpDesignerGenerationResult(builder.ToString(), validation);
    }

    private static void ValidateEffectiveNames(
        string namespaceName,
        string className,
        DesignDocumentValidationResult validation)
    {
        if (string.IsNullOrWhiteSpace(className))
            validation.AddError("The effective generated class name cannot be empty.");
        else if (!CSharpIdentifierSanitizer.IsValidIdentifier(className))
            validation.AddError($"The effective generated class name '{className}' is not a valid C# identifier.");

        if (!string.IsNullOrWhiteSpace(namespaceName)
            && !namespaceName.Split('.').All(CSharpIdentifierSanitizer.IsValidIdentifier))
        {
            validation.AddError($"The effective generated namespace '{namespaceName}' is not a valid C# namespace.");
        }
    }

    private static void ValidatePropertyNames(
        IEnumerable<DesignControlNode> controls,
        DesignDocumentValidationResult validation)
    {
        foreach (var control in controls)
        {
            ValidatePropertyNames(control.Properties.Keys, $"control '{control.Name}'", validation);

            ValidatePropertyNames(control.Children, validation);
        }
    }

    private static void ValidatePropertyNames(
        IEnumerable<string> properties,
        string owner,
        DesignDocumentValidationResult validation)
    {
        foreach (var property in properties)
        {
            if (!IsValidPropertyPath(property))
                validation.AddError($"Property name '{property}' on {owner} is not a valid C# identifier.");
        }
    }

    private static bool IsValidPropertyPath(string propertyPath)
        => !string.IsNullOrWhiteSpace(propertyPath)
        && propertyPath.Split('.').All(CSharpIdentifierSanitizer.IsValidIdentifier);

    private static IEnumerable<DesignControlNode> FlattenControls(IEnumerable<DesignControlNode> controls)
    {
        foreach (var control in controls)
        {
            if (IsSplitPanel(control))
            {
                foreach (var splitPanelChild in FlattenControls(control.Children))
                    yield return splitPanelChild;

                continue;
            }

            yield return control;

            foreach (var child in FlattenControls(control.Children))
                yield return child;
        }
    }

    private static void WriteControlInitialization(
        CodeWriter writer,
        DesignControlNode control,
        string controlExpression,
        DesignDocumentValidationResult validation)
    {
        writer.WriteLine($"        {controlExpression}.Name = {CSharpLiteralWriter.WriteStringLiteral(control.Name)};");
        writer.WriteLine($"        {controlExpression}.Bounds = new System.Drawing.Rectangle({control.Bounds.X}, {control.Bounds.Y}, {control.Bounds.Width}, {control.Bounds.Height});");

        if (!control.Properties.ContainsKey(DockPropertyName))
            writer.WriteLine($"        {controlExpression}.Dock = ModernFormsNext.DockStyle.None;");

        foreach (var property in control.Properties)
        {
            if (GeneratedControlProperties.Contains(property.Key) || DesignerOnlyProperties.Contains(property.Key))
                continue;

            WritePropertyAssignment(writer, controlExpression, property.Key, property.Value, control.Name, validation);
        }

        writer.WriteLine();
    }

    private static void WritePropertyAssignment(
        CodeWriter writer,
        string targetExpression,
        string propertyPath,
        DesignPropertyValue? value,
        string ownerName,
        DesignDocumentValidationResult validation)
    {
        try
        {
            writer.WriteLine($"        {targetExpression}.{propertyPath} = {CSharpLiteralWriter.WriteValue(value)};");
        }
        catch (NotSupportedException ex)
        {
            validation.AddWarning($"Property '{propertyPath}' on '{ownerName}' was skipped during code generation: {ex.Message}");
        }
        catch (FormatException ex)
        {
            validation.AddWarning($"Property '{propertyPath}' on '{ownerName}' was skipped during code generation because its value is not valid: {ex.Message}");
        }
        catch (InvalidCastException ex)
        {
            validation.AddWarning($"Property '{propertyPath}' on '{ownerName}' was skipped during code generation because its value cannot be converted: {ex.Message}");
        }
        catch (OverflowException ex)
        {
            validation.AddWarning($"Property '{propertyPath}' on '{ownerName}' was skipped during code generation because its value is outside the supported range: {ex.Message}");
        }
    }

    private static void WriteControlEvents(CodeWriter writer, DesignControlNode control, string controlExpression)
    {
        var emittedAny = false;

        foreach (var eventBinding in control.Events)
        {
            if (string.IsNullOrWhiteSpace(eventBinding.Value))
                continue;

            writer.WriteLine($"        {controlExpression}.{eventBinding.Key} += this.{eventBinding.Value};");
            emittedAny = true;
        }

        if (emittedAny)
            writer.WriteLine();
    }

    private static void WriteControlAdds(
        CodeWriter writer,
        IEnumerable<DesignControlNode> controls,
        string parentExpression,
        DesignControlNode? parentNode,
        IReadOnlyDictionary<DesignControlNode, string> controlExpressions)
    {
        foreach (var control in controls)
        {
            if (IsSplitPanel(control))
            {
                var splitPanelExpression = parentExpression + (IsSplitPanel1(control) ? ".Panel1" : ".Panel2");
                WriteControlAdds(writer, control.Children, splitPanelExpression, control, controlExpressions);
                continue;
            }

            var controlExpression = controlExpressions[control];
            var addCollection = IsTabPage(control) ? "TabPages" : "Controls";
            writer.WriteLine($"        {parentExpression}.{addCollection}.Add({controlExpression});");
            WriteTableLayoutAssignments(writer, parentNode, parentExpression, control, controlExpression);
            WriteControlAdds(writer, control.Children, controlExpression, control, controlExpressions);
        }
    }

    private static void WriteTableLayoutAssignments(
        CodeWriter writer,
        DesignControlNode? parentNode,
        string parentExpression,
        DesignControlNode control,
        string controlExpression)
    {
        if (parentNode is null || !IsType(parentNode, "TableLayoutPanel"))
            return;

        if (control.Properties.TryGetValue("TableColumn", out var column))
            writer.WriteLine($"        {parentExpression}.SetColumn({controlExpression}, {CSharpLiteralWriter.WriteValue(column)});");

        if (control.Properties.TryGetValue("TableRow", out var row))
            writer.WriteLine($"        {parentExpression}.SetRow({controlExpression}, {CSharpLiteralWriter.WriteValue(row)});");

        if (control.Properties.TryGetValue("TableColumnSpan", out var columnSpan))
            writer.WriteLine($"        {parentExpression}.SetColumnSpan({controlExpression}, {CSharpLiteralWriter.WriteValue(columnSpan)});");

        if (control.Properties.TryGetValue("TableRowSpan", out var rowSpan))
            writer.WriteLine($"        {parentExpression}.SetRowSpan({controlExpression}, {CSharpLiteralWriter.WriteValue(rowSpan)});");
    }

    private static bool IsSplitPanel(DesignControlNode node)
        => IsRole(node, DesignNodeRoleNames.SplitContainerPanel1)
        || IsRole(node, DesignNodeRoleNames.SplitContainerPanel2);

    private static bool IsSplitPanel1(DesignControlNode node)
        => IsRole(node, DesignNodeRoleNames.SplitContainerPanel1);

    private static bool IsTabPage(DesignControlNode node)
        => IsType(node, "TabPage");

    private static bool IsRole(DesignControlNode node, string role)
        => node.Properties.TryGetValue(DesignNodeRoleNames.RolePropertyName, out var property)
        && property.Value is string value
        && string.Equals(value, role, StringComparison.Ordinal);

    private static bool IsType(DesignControlNode node, string shortTypeName)
        => string.Equals(node.TypeName, shortTypeName, StringComparison.Ordinal)
        || node.TypeName.EndsWith("." + shortTypeName, StringComparison.Ordinal);

    private readonly struct CodeWriter
    {
        private readonly StringBuilder builder;
        private readonly string newline;

        public CodeWriter(StringBuilder builder, string newline)
        {
            this.builder = builder;
            this.newline = string.IsNullOrEmpty(newline) ? "\n" : newline;
        }

        public void WriteLine(string value = "")
        {
            builder.Append(value);
            builder.Append(newline);
        }
    }
}
