using System.Globalization;
using System.Text;
using ModernFormsNext.CodeGeneration.Utilities;
using ModernFormsNext.Designing;

namespace ModernFormsNext.CodeGeneration.CSharp;

/// <summary>
/// Generates ModernFormsNext C# designer partial classes from neutral design documents.
/// </summary>
/// <remarks>
/// The generator emits WinForms-like initialization code while using the actual
/// ModernFormsNext runtime API available today: <c>Bounds</c>, <c>Controls</c>,
/// <c>Dock</c>, <c>Name</c>, <c>Text</c>, and <c>Size</c>. It emits an explicit
/// <c>DockStyle.None</c> when the design document has no dock value so runtime
/// constructor defaults on specialized controls do not change designer-authored
/// layout. Child collections are mapped from persisted front-to-back order to the runtime
/// collection's last-index-is-front representation. Sequential flow, table, and tab containers
/// retain authored order because their collection order also defines their content sequence.
/// It does not depend on Visual Studio SDK services and is deterministic for a
/// given document and option set.
/// </remarks>
public sealed class CSharpDesignerGenerator
{
    private const string DockPropertyName = "Dock";

    private static readonly HashSet<string> GeneratedControlProperties = new(StringComparer.Ordinal)
    {
        "Bounds",
        "Name"
    };

    private static readonly HashSet<string> DesignerOnlyProperties = new(StringComparer.Ordinal)
    {
        DesignNodeRoleNames.RolePropertyName,
        DesignNodeRoleNames.DisplayNamePropertyName,
        DesignNodeRoleNames.DisplayTypePropertyName,
        "TableColumn",
        "TableRow",
        "TableColumnSpan",
        "TableRowSpan"
    };

    private static readonly HashSet<string> GeneratedRootProperties = new(StringComparer.Ordinal)
    {
        "Name",
        "ClientSize",
        "Size"
    };

    /// <summary>
    /// Generates C# designer code for a document.
    /// </summary>
    /// <param name="document">The designer document to generate from.</param>
    /// <param name="options">Optional generation settings.</param>
    /// <returns>The generation result with code and validation messages.</returns>
    public CSharpDesignerGenerationResult Generate(
        DesignDocument document,
        CSharpDesignerGenerationOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(document);

        options ??= new CSharpDesignerGenerationOptions();

        var validation = new DesignDocumentValidator().Validate(document);
        var namespaceName = options.NamespaceOverride ?? document.Namespace;
        var className = options.ClassNameOverride ?? document.ClassName;

        ValidateEffectiveNames(namespaceName, className, validation);
        ValidatePropertyNames(document.Properties.Keys, "design root", validation);
        ValidatePropertyNames(document.Controls, validation);

        if (!validation.IsValid)
            return new CSharpDesignerGenerationResult(string.Empty, validation);

        var builder = new StringBuilder();
        var writer = new CodeWriter(builder, options.NewLine);
        var controls = FlattenControls(document.Controls).ToArray();
        var controlExpressions = controls.ToDictionary(
            control => control,
            control => control.MemberVisibility == DesignerMemberVisibility.None ? control.Name : $"this.{control.Name}");

        if (options.EmitAutoGeneratedHeader)
        {
            writer.WriteLine("// <auto-generated />");
        }

        if (options.EmitDesignerMetadataHeader)
        {
            writer.WriteLine("// ModernFormsNext designer file.");

            if (!string.IsNullOrWhiteSpace(options.SourceFilePath))
                writer.WriteLine($"// Source: {options.SourceFilePath}");

            if (!string.IsNullOrWhiteSpace(options.DesignHash))
                writer.WriteLine($"// DesignHash: {options.DesignHash}");
        }

        if (options.EmitAutoGeneratedHeader || options.EmitDesignerMetadataHeader)
            writer.WriteLine();

        writer.WriteLine("using ModernFormsNext;");
        writer.WriteLine();

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            writer.WriteLine($"namespace {namespaceName};");
            writer.WriteLine();
        }

        writer.WriteLine($"public partial class {className}");
        writer.WriteLine("{");

        foreach (var control in controls.Where(control => control.MemberVisibility != DesignerMemberVisibility.None))
        {
            var modifier = CSharpMemberVisibilityWriter.WriteFieldModifier(control.MemberVisibility);
            writer.WriteLine($"    {modifier} {control.TypeName} {control.Name} = null!;");
        }

        if (controls.Length > 0)
            writer.WriteLine();

        writer.WriteLine("    private void InitializeComponent()");
        writer.WriteLine("    {");

        foreach (var control in controls)
        {
            if (control.MemberVisibility == DesignerMemberVisibility.None)
                writer.WriteLine($"        var {control.Name} = new {control.TypeName}();");
            else
                writer.WriteLine($"        this.{control.Name} = new {control.TypeName}();");
        }

        if (controls.Length > 0)
            writer.WriteLine();

        foreach (var control in controls)
            WriteControlInitialization(writer, control, controlExpressions[control], validation);

        foreach (var control in controls)
            WriteControlEvents(writer, control, controlExpressions[control]);

        WriteControlAdds(writer, document.Controls, "this", parentNode: null, controlExpressions);

        if (controls.Length > 0)
            writer.WriteLine();

        var rootName = string.IsNullOrWhiteSpace(document.FormName) ? className : document.FormName;
        writer.WriteLine($"        this.Name = {CSharpLiteralWriter.WriteStringLiteral(rootName)};");

        if (document.RootKind == DesignRootKind.Form)
            writer.WriteLine($"        this.Text = {CSharpLiteralWriter.WriteStringLiteral(rootName)};");

        writer.WriteLine($"        this.Size = new System.Drawing.Size({document.Size.Width}, {document.Size.Height});");

        foreach (var property in document.Properties)
        {
            if (GeneratedRootProperties.Contains(property.Key)
                || document.RootKind == DesignRootKind.Form && string.Equals(property.Key, "Text", StringComparison.Ordinal))
                continue;

            WritePropertyAssignment(writer, "this", property.Key, property.Value, "design root", validation);
        }

        foreach (var eventBinding in document.Events)
        {
            if (string.IsNullOrWhiteSpace(eventBinding.Value))
                continue;

            writer.WriteLine($"        this.{eventBinding.Key} += this.{eventBinding.Value};");
        }

        writer.WriteLine("    }");
        writer.WriteLine("}");

        return new CSharpDesignerGenerationResult(builder.ToString(), validation);
    }

    private static void ValidateEffectiveNames(
        string namespaceName,
        string className,
        DesignDocumentValidationResult validation)
    {
        if (string.IsNullOrWhiteSpace(className))
            validation.AddError("The effective generated class name cannot be empty.");
        else if (!CSharpIdentifierSanitizer.IsValidIdentifier(className))
            validation.AddError($"The effective generated class name '{className}' is not a valid C# identifier.");

        if (!string.IsNullOrWhiteSpace(namespaceName)
            && !namespaceName.Split('.').All(CSharpIdentifierSanitizer.IsValidIdentifier))
        {
            validation.AddError($"The effective generated namespace '{namespaceName}' is not a valid C# namespace.");
        }
    }

    private static void ValidatePropertyNames(
        IReadOnlyList<DesignControlNode> controls,
        DesignDocumentValidationResult validation)
    {
        foreach (var control in controls)
        {
            ValidatePropertyNames(control.Properties.Keys, $"control '{control.Name}'", validation);

            ValidatePropertyNames(control.Children, validation);
        }
    }

    private static void ValidatePropertyNames(
        IEnumerable<string> properties,
        string owner,
        DesignDocumentValidationResult validation)
    {
        foreach (var property in properties)
        {
            if (!IsValidPropertyPath(property))
                validation.AddError($"Property name '{property}' on {owner} is not a valid C# identifier.");
        }
    }

    private static bool IsValidPropertyPath(string propertyPath)
        => !string.IsNullOrWhiteSpace(propertyPath)
        && propertyPath.Split('.').All(CSharpIdentifierSanitizer.IsValidIdentifier);

    private static IEnumerable<DesignControlNode> FlattenControls(IEnumerable<DesignControlNode> controls)
    {
        foreach (var control in controls)
        {
            if (IsSplitPanel(control))
            {
                foreach (var splitPanelChild in FlattenControls(control.Children))
                    yield return splitPanelChild;

                continue;
            }

            yield return control;

            foreach (var child in FlattenControls(control.Children))
                yield return child;
        }
    }

    private static void WriteControlInitialization(
        CodeWriter writer,
        DesignControlNode control,
        string controlExpression,
        DesignDocumentValidationResult validation)
    {
        writer.WriteLine($"        {controlExpression}.Name = {CSharpLiteralWriter.WriteStringLiteral(control.Name)};");
        writer.WriteLine($"        {controlExpression}.Bounds = new System.Drawing.Rectangle({control.Bounds.X}, {control.Bounds.Y}, {control.Bounds.Width}, {control.Bounds.Height});");

        if (!control.Properties.ContainsKey(DockPropertyName))
            writer.WriteLine($"        {controlExpression}.Dock = ModernFormsNext.DockStyle.None;");

        foreach (var property in control.Properties)
        {
            if (GeneratedControlProperties.Contains(property.Key) || DesignerOnlyProperties.Contains(property.Key))
                continue;

            if (string.Equals(property.Key, InteractionEffectDesignValue.PropertyName, StringComparison.Ordinal))
            {
                WriteInteractionEffects(writer, controlExpression, property.Value, control.Name, validation);
                continue;
            }

            WritePropertyAssignment(writer, controlExpression, property.Key, property.Value, control.Name, validation);
        }

        writer.WriteLine();
    }

    private static void WriteInteractionEffects(
        CodeWriter writer,
        string targetExpression,
        DesignPropertyValue value,
        string ownerName,
        DesignDocumentValidationResult validation)
    {
        if (!InteractionEffectDesignValue.TryRead(value, out IReadOnlyList<DesignPropertyValue> effects, out string? error))
        {
            validation.AddWarning($"InteractionEffects on '{ownerName}' was skipped: {error}");
            return;
        }

        for (int index = 0; index < effects.Count; index++)
        {
            try
            {
                string expression = WriteInteractionEffect(effects[index]);
                writer.WriteLine($"        {targetExpression}.InteractionEffects.Add({expression});");
            }
            catch (Exception exception) when (exception is NotSupportedException
                or FormatException
                or InvalidCastException
                or OverflowException)
            {
                validation.AddWarning(
                    $"InteractionEffects.Item{index} on '{ownerName}' was skipped: {exception.Message}");
            }
        }
    }

    private static string WriteInteractionEffect(DesignPropertyValue effect)
    {
        IReadOnlyDictionary<string, DesignPropertyValue> properties = effect.ObjectProperties
            ?? throw new FormatException("The effect description does not contain properties.");
        string typeName = effect.ObjectTypeName ?? string.Empty;

        if (IsEffectType(typeName, "RippleEffect"))
        {
            ValidateEffectProperties(properties,
                "Enabled", "ColorArgb", "DurationMilliseconds", "StartFromPointer", "RadiusMode",
                "FixedRadius", "Layer", "MaxConcurrentRipples", "OverflowPolicy");
            int argb = ReadInt(properties, "ColorArgb", unchecked((int)0x5AFFFFFF));
            uint color = unchecked((uint)argb);
            return "new ModernFormsNext.Animations.RippleEffect { "
                + $"Enabled = {ReadBoolLiteral(properties, "Enabled", true)}, "
                + $"Color = System.Drawing.Color.FromArgb({color >> 24}, {(color >> 16) & 0xFF}, {(color >> 8) & 0xFF}, {color & 0xFF}), "
                + $"Duration = System.TimeSpan.FromMilliseconds({ReadDoubleLiteral(properties, "DurationMilliseconds", 450d)}), "
                + $"StartFromPointer = {ReadBoolLiteral(properties, "StartFromPointer", true)}, "
                + $"RadiusMode = {ReadEnumLiteral(properties, "RadiusMode", "ModernFormsNext.Animations.RippleRadiusMode", "CoverControl", "CoverControl", "Fixed")}, "
                + $"FixedRadius = {ReadFloatLiteral(properties, "FixedRadius", 48d)}, "
                + $"Layer = {ReadEnumLiteral(properties, "Layer", "ModernFormsNext.Animations.RippleLayer", "AboveBackgroundBelowContent", "AboveBackgroundBelowContent", "AboveContent")}, "
                + $"MaxConcurrentRipples = {ReadInt(properties, "MaxConcurrentRipples", 4)}, "
                + $"OverflowPolicy = {ReadEnumLiteral(properties, "OverflowPolicy", "ModernFormsNext.Animations.RippleOverflowPolicy", "RemoveOldest", "RemoveOldest", "RemoveNewest", "IgnoreNew", "ReplaceAll")} "
                + "}";
        }

        if (IsEffectType(typeName, "PressScaleEffect"))
        {
            ValidateEffectProperties(properties,
                "Enabled", "PressedScale", "PressDurationMilliseconds", "ReleaseDurationMilliseconds");
            return "new ModernFormsNext.Animations.PressScaleEffect { "
                + $"Enabled = {ReadBoolLiteral(properties, "Enabled", true)}, "
                + $"PressedScale = {ReadFloatLiteral(properties, "PressedScale", 0.97d)}, "
                + $"PressDuration = System.TimeSpan.FromMilliseconds({ReadDoubleLiteral(properties, "PressDurationMilliseconds", 80d)}), "
                + $"ReleaseDuration = System.TimeSpan.FromMilliseconds({ReadDoubleLiteral(properties, "ReleaseDurationMilliseconds", 120d)}) "
                + "}";
        }

        throw new NotSupportedException($"Interaction effect type '{typeName}' is not registered for code generation.");
    }

    private static void ValidateEffectProperties(
        IReadOnlyDictionary<string, DesignPropertyValue> properties,
        params string[] supportedNames)
    {
        var supported = supportedNames.ToHashSet(StringComparer.Ordinal);
        string? unsupported = properties.Keys.FirstOrDefault(name => !supported.Contains(name));
        if (unsupported is not null)
            throw new NotSupportedException($"Property '{unsupported}' is not supported for this interaction effect.");
    }

    private static bool IsEffectType(string typeName, string shortName)
        => string.Equals(typeName, shortName, StringComparison.Ordinal)
        || string.Equals(typeName, "ModernFormsNext.Animations." + shortName, StringComparison.Ordinal);

    private static int ReadInt(
        IReadOnlyDictionary<string, DesignPropertyValue> properties,
        string name,
        int fallback)
    {
        if (!properties.TryGetValue(name, out DesignPropertyValue? value))
            return fallback;
        if (value.Kind != DesignPropertyValueKind.Int32 || value.Value is not int result)
            throw new FormatException($"Property '{name}' must be a 32-bit integer.");
        return result;
    }

    private static string ReadDoubleLiteral(
        IReadOnlyDictionary<string, DesignPropertyValue> properties,
        string name,
        double fallback)
    {
        double result;
        if (!properties.TryGetValue(name, out DesignPropertyValue? value))
        {
            result = fallback;
        }
        else if (value.Kind is DesignPropertyValueKind.Double or DesignPropertyValueKind.Int32)
        {
            result = Convert.ToDouble(value.Value, CultureInfo.InvariantCulture);
        }
        else
        {
            throw new FormatException($"Property '{name}' must be numeric.");
        }
        if (!double.IsFinite(result))
            throw new FormatException($"Property '{name}' must be finite.");
        return result.ToString("R", CultureInfo.InvariantCulture);
    }

    private static string ReadFloatLiteral(
        IReadOnlyDictionary<string, DesignPropertyValue> properties,
        string name,
        double fallback)
    {
        float result = (float)double.Parse(
            ReadDoubleLiteral(properties, name, fallback),
            CultureInfo.InvariantCulture);
        if (!float.IsFinite(result))
            throw new FormatException($"Property '{name}' must fit in a finite single-precision value.");
        return result.ToString("R", CultureInfo.InvariantCulture) + "f";
    }

    private static string ReadBoolLiteral(
        IReadOnlyDictionary<string, DesignPropertyValue> properties,
        string name,
        bool fallback)
    {
        if (!properties.TryGetValue(name, out DesignPropertyValue? value))
            return fallback ? "true" : "false";
        if (value.Kind != DesignPropertyValueKind.Boolean || value.Value is not bool result)
            throw new FormatException($"Property '{name}' must be a Boolean.");
        return result ? "true" : "false";
    }

    private static string ReadEnumLiteral(
        IReadOnlyDictionary<string, DesignPropertyValue> properties,
        string name,
        string enumTypeName,
        string fallbackMember,
        params string[] supportedMembers)
    {
        if (!properties.TryGetValue(name, out DesignPropertyValue? value))
            return enumTypeName + "." + fallbackMember;
        string shortTypeName = enumTypeName.Split('.').Last();
        string member = value.GetString();
        if (value.Kind != DesignPropertyValueKind.Enum
            || (!string.Equals(value.EnumTypeName, enumTypeName, StringComparison.Ordinal)
                && !string.Equals(value.EnumTypeName, shortTypeName, StringComparison.Ordinal))
            || !supportedMembers.Contains(member, StringComparer.Ordinal))
        {
            throw new FormatException($"Property '{name}' is not a supported {shortTypeName} value.");
        }
        return enumTypeName + "." + member;
    }

    private static void WritePropertyAssignment(
        CodeWriter writer,
        string targetExpression,
        string propertyPath,
        DesignPropertyValue? value,
        string ownerName,
        DesignDocumentValidationResult validation)
    {
        try
        {
            writer.WriteLine($"        {targetExpression}.{propertyPath} = {CSharpLiteralWriter.WriteValue(value)};");
        }
        catch (NotSupportedException ex)
        {
            validation.AddWarning($"Property '{propertyPath}' on '{ownerName}' was skipped during code generation: {ex.Message}");
        }
        catch (FormatException ex)
        {
            validation.AddWarning($"Property '{propertyPath}' on '{ownerName}' was skipped during code generation because its value is not valid: {ex.Message}");
        }
        catch (InvalidCastException ex)
        {
            validation.AddWarning($"Property '{propertyPath}' on '{ownerName}' was skipped during code generation because its value cannot be converted: {ex.Message}");
        }
        catch (OverflowException ex)
        {
            validation.AddWarning($"Property '{propertyPath}' on '{ownerName}' was skipped during code generation because its value is outside the supported range: {ex.Message}");
        }
    }

    private static void WriteControlEvents(CodeWriter writer, DesignControlNode control, string controlExpression)
    {
        var emittedAny = false;

        foreach (var eventBinding in control.Events)
        {
            if (string.IsNullOrWhiteSpace(eventBinding.Value))
                continue;

            writer.WriteLine($"        {controlExpression}.{eventBinding.Key} += this.{eventBinding.Value};");
            emittedAny = true;
        }

        if (emittedAny)
            writer.WriteLine();
    }

    private static void WriteControlAdds(
        CodeWriter writer,
        IReadOnlyList<DesignControlNode> controls,
        string parentExpression,
        DesignControlNode? parentNode,
        IReadOnlyDictionary<DesignControlNode, string> controlExpressions)
    {
        // Runtime ControlCollection uses its last index as the visual/docking front, whereas the
        // document stores the front-most node at index zero. Map that Z-order explicitly for
        // ordinary containers. Flow/table/tab collections are sequential content models, so their
        // authored order must stay forward and must not be affected by a global reversal.
        foreach (var control in EnumerateControlAddOrder(controls, parentNode))
        {
            if (IsSplitPanel(control))
            {
                var splitPanelExpression = parentExpression + (IsSplitPanel1(control) ? ".Panel1" : ".Panel2");
                WriteControlAdds(writer, control.Children, splitPanelExpression, control, controlExpressions);
                continue;
            }

            var controlExpression = controlExpressions[control];
            var addCollection = IsTabPage(control) ? "TabPages" : "Controls";
            writer.WriteLine($"        {parentExpression}.{addCollection}.Add({controlExpression});");
            WriteTableLayoutAssignments(writer, parentNode, parentExpression, control, controlExpression);
            WriteControlAdds(writer, control.Children, controlExpression, control, controlExpressions);
        }
    }

    private static IEnumerable<DesignControlNode> EnumerateControlAddOrder(
        IReadOnlyList<DesignControlNode> controls,
        DesignControlNode? parentNode)
    {
        if (parentNode is not null && PreservesSequentialChildOrder(parentNode))
        {
            for (var index = 0; index < controls.Count; index++)
                yield return controls[index];

            yield break;
        }

        for (var index = controls.Count - 1; index >= 0; index--)
            yield return controls[index];
    }

    private static bool PreservesSequentialChildOrder(DesignControlNode node)
        => IsType(node, "FlowLayoutPanel")
        || IsType(node, "TableLayoutPanel")
        || IsType(node, "TabControl");

    private static void WriteTableLayoutAssignments(
        CodeWriter writer,
        DesignControlNode? parentNode,
        string parentExpression,
        DesignControlNode control,
        string controlExpression)
    {
        if (parentNode is null || !IsType(parentNode, "TableLayoutPanel"))
            return;

        if (control.Properties.TryGetValue("TableColumn", out var column))
            writer.WriteLine($"        {parentExpression}.SetColumn({controlExpression}, {CSharpLiteralWriter.WriteValue(column)});");

        if (control.Properties.TryGetValue("TableRow", out var row))
            writer.WriteLine($"        {parentExpression}.SetRow({controlExpression}, {CSharpLiteralWriter.WriteValue(row)});");

        if (control.Properties.TryGetValue("TableColumnSpan", out var columnSpan))
            writer.WriteLine($"        {parentExpression}.SetColumnSpan({controlExpression}, {CSharpLiteralWriter.WriteValue(columnSpan)});");

        if (control.Properties.TryGetValue("TableRowSpan", out var rowSpan))
            writer.WriteLine($"        {parentExpression}.SetRowSpan({controlExpression}, {CSharpLiteralWriter.WriteValue(rowSpan)});");
    }

    private static bool IsSplitPanel(DesignControlNode node)
        => IsRole(node, DesignNodeRoleNames.SplitContainerPanel1)
        || IsRole(node, DesignNodeRoleNames.SplitContainerPanel2);

    private static bool IsSplitPanel1(DesignControlNode node)
        => IsRole(node, DesignNodeRoleNames.SplitContainerPanel1);

    private static bool IsTabPage(DesignControlNode node)
        => IsType(node, "TabPage");

    private static bool IsRole(DesignControlNode node, string role)
        => node.Properties.TryGetValue(DesignNodeRoleNames.RolePropertyName, out var property)
        && property.Value is string value
        && string.Equals(value, role, StringComparison.Ordinal);

    private static bool IsType(DesignControlNode node, string shortTypeName)
        => string.Equals(node.TypeName, shortTypeName, StringComparison.Ordinal)
        || node.TypeName.EndsWith("." + shortTypeName, StringComparison.Ordinal);

    private readonly struct CodeWriter
    {
        private readonly StringBuilder builder;
        private readonly string newline;

        public CodeWriter(StringBuilder builder, string newline)
        {
            this.builder = builder;
            this.newline = string.IsNullOrEmpty(newline) ? "\n" : newline;
        }

        public void WriteLine(string value = "")
        {
            builder.Append(value);
            builder.Append(newline);
        }
    }
}
