namespace ModernFormsNext.CodeGeneration.CSharp;

/// <summary>
/// Configures C# designer file generation.
/// </summary>
public sealed class CSharpDesignerGenerationOptions
{
    /// <summary>
    /// Gets or sets an optional namespace that replaces the namespace stored in the design document.
    /// </summary>
    public string? NamespaceOverride { get; set; }

    /// <summary>
    /// Gets or sets an optional class name that replaces the class name stored in the design document.
    /// </summary>
    public string? ClassNameOverride { get; set; }

    /// <summary>
    /// Gets or sets the newline sequence used in generated code.
    /// </summary>
    /// <remarks>
    /// The default is line-feed to keep generator output deterministic across operating systems.
    /// </remarks>
    public string NewLine { get; set; } = "\n";

    /// <summary>
    /// Gets or sets a value indicating whether the <c>// &lt;auto-generated /&gt;</c> header is emitted.
    /// </summary>
    public bool EmitAutoGeneratedHeader { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether ModernFormsNext designer metadata comments are emitted.
    /// </summary>
    /// <remarks>
    /// These comments are intended for future round-trip synchronization and manual-change
    /// detection. They are informational and do not affect generated C# semantics.
    /// </remarks>
    public bool EmitDesignerMetadataHeader { get; set; } = true;

    /// <summary>
    /// Gets or sets the optional source <c>.mfdesign</c> file path or display name written to the generated header.
    /// </summary>
    public string? SourceFilePath { get; set; }

    /// <summary>
    /// Gets or sets an optional hash of the design model used to produce the generated file.
    /// </summary>
    public string? DesignHash { get; set; }
}
