name: Bug report
description: Report a bug
title: "[BUG] "
body:
  - type: textarea
    label: Describe the bug
  - type: textarea
    label: Steps to reproduce
  - type: textarea
    label: Expected behavior
