<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<NoWarn>$(NoWarn);CA1416</NoWarn>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

		<PackageId>ModernFormsNext.WindowKit</PackageId>
		<Title>ModernFormsNext WindowKit</Title>
		<Version>$(ModernFormsNextPackageVersion)</Version>
		<Product>ModernFormsNext.WindowKit</Product>

		<Description>Core windowing abstraction layer for ModernFormsNext.</Description>

		<PackageTags>ui;windowing;desktop;framework;modernforms;windowkit</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\icon.png" Pack="true" PackagePath="\" Link="icon.png" />
		<None Include="..\README.md" Pack="true" PackagePath="\" Link="README.md" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ModernFormsNext.WindowKit.Backend\ModernFormsNext.WindowKit.Backend.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201" PrivateAssets="All" />
		<PackageReference Include="SkiaSharp" Version="3.119.2" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.2" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Avalonia.Mac\**\*.cs" />
		<Compile Remove="Avalonia.X11\**\*.cs" />
		<Compile Remove="Partials\Mac\**\*.cs" />
		<Compile Remove="Partials\X11\**\*.cs" />
		<Compile Remove="Avalonia.Win32\**\*.cs" />
		<Compile Remove="Partials\Win32\**\*.cs" />
	</ItemGroup>

</Project>
