<#
.SYNOPSIS
Validates MicroCom generation and IDE/clean contracts in an owned temporary project.
.DESCRIPTION
Copies the generator sources into an isolated fixture. No repository source or
real generator output is changed. Requires the repository's .NET SDK and restore.
#>
[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$parent = Join-Path $root 'artifacts/build-architecture-tests'
$fixture = Join-Path $parent ([Guid]::NewGuid().ToString('N'))
$checks = 0

function Assert-Contract([bool]$Condition, [string]$Message) {
    if (-not $Condition) { throw $Message }
    $script:checks++
}
function Invoke-Fixture([string[]]$Arguments) {
    $output = & dotnet @Arguments 2>&1
    if ($LASTEXITCODE -ne 0) { throw ($output -join [Environment]::NewLine) }
    return ($output -join [Environment]::NewLine)
}
function Generate {
    $null = Invoke-Fixture @('msbuild', $project, '-t:GenerateAvaloniaNativeComInterop', '-v:q', '-m:4', '/p:UseSharedCompilation=false')
    Assert-Contract (Test-Path $generated) 'Generation must produce the per-instance source.'
}

try {
    $null = New-Item -ItemType Directory -Path $fixture
    $toolDirectory = Join-Path $fixture 'Generator'
    $null = New-Item -ItemType Directory -Path $toolDirectory
    $sourceTool = Join-Path $root 'ModernFormsNext.WindowKit.Backend.Tools.MicroComGenerator'
    Get-ChildItem -LiteralPath $sourceTool -File | Where-Object {$_.Extension -in '.cs', '.csproj'} |
        Copy-Item -Destination $toolDirectory
    $generatorProject = Join-Path $toolDirectory 'ModernFormsNext.WindowKit.Backend.Tools.MicroComGenerator.csproj'
    $idl = Join-Path $fixture 'win32.idl'
    $snapshot = Join-Path $fixture 'Snapshot.cs'
    Copy-Item -LiteralPath (Join-Path $root 'win32.idl') -Destination $idl
    Copy-Item -LiteralPath (Join-Path $root 'ModernFormsNext.WindowKit.Backend.Windows/Generated/Windows.Interop.Generated.cs') -Destination $snapshot
    $snapshotHash = (Get-FileHash $snapshot).Hash
    $project = Join-Path $fixture 'Fixture.csproj'
    $targets = [Security.SecurityElement]::Escape((Join-Path $root 'build/MicroCom.targets'))
    $generatorXml = [Security.SecurityElement]::Escape($generatorProject)
    @"
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework><IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <MicroComGeneratorProject>$generatorXml</MicroComGeneratorProject>
  </PropertyGroup>
  <ItemGroup><AvnComIdl Include="win32.idl" SnapshotFile="Snapshot.cs" /></ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <Import Project="$targets" />
</Project>
"@ | Set-Content -LiteralPath $project
    $null = Invoke-Fixture @('restore', $project, '-v:q')
    $generated = Join-Path $fixture 'obj/Debug/net10.0/MicroCom/Windows.Interop.Generated.cs'
    $design = Invoke-Fixture @('msbuild', $project, '-p:DesignTimeBuild=true', '-getItem:Compile') | ConvertFrom-Json
    Assert-Contract (@($design.Items.Compile).Count -eq 1 -and $design.Items.Compile[0].Identity -eq 'Snapshot.cs') 'Clean IDE evaluation must use the read-only snapshot.'
    Assert-Contract (-not (Test-Path $generated)) 'Design-time evaluation must not generate code.'
    $designInputs = Invoke-Fixture @('msbuild', $project, '-p:DesignTimeBuild=true', '-t:CollectMicroComDesignTimeInputs', '-getItem:UpToDateCheckInput') | ConvertFrom-Json
    Assert-Contract ([bool]($designInputs.Items.UpToDateCheckInput.Identity -like '*MicroComGenerator.dll')) 'IDE inputs must include the resolved generator assembly.'
    Assert-Contract (-not (Test-Path (Join-Path $toolDirectory 'bin/Debug/net10.0/ModernFormsNext.WindowKit.Backend.Tools.MicroComGenerator.dll'))) 'Collecting IDE inputs must not build the tool.'

    Generate
    Assert-Contract ((Get-FileHash $generated).Hash -eq $snapshotHash) 'Generated bytes must match the tracked snapshot.'
    $designInputs = Invoke-Fixture @('msbuild', $project, '-p:DesignTimeBuild=true', '-t:CollectMicroComDesignTimeInputs', '-getItem:UpToDateCheckInput') | ConvertFrom-Json
    Assert-Contract ([bool]($designInputs.Items.UpToDateCheckInput.Identity -like '*.deps.json')) 'IDE inputs must include the resolved runtime payload.'
    $stamp = (Get-Item $generated).LastWriteTimeUtc
    Generate
    Assert-Contract ((Get-Item $generated).LastWriteTimeUtc -eq $stamp) 'An unchanged build must skip generation.'

    # An invalid C# file here also catches an accidentally widened compiler glob.
    Set-Content (Join-Path $toolDirectory 'obj/irrelevant.cs') 'this is deliberately not C#'
    Generate
    Assert-Contract ((Get-Item $generated).LastWriteTimeUtc -eq $stamp) 'Generator obj sources must not invalidate generation.'

    Add-Content -LiteralPath $idl '// Incremental input validation.'
    Generate
    Assert-Contract ((Get-Item $generated).LastWriteTimeUtc -gt $stamp) 'An IDL change must regenerate.'
    Assert-Contract ((Get-FileHash $generated).Hash -eq $snapshotHash) 'An IDL comment must not change the generated bytes.'
    $stamp = (Get-Item $generated).LastWriteTimeUtc

    Add-Content -LiteralPath (Join-Path $toolDirectory 'Program.cs') '// Incremental generator validation.'
    Generate
    Assert-Contract ((Get-Item $generated).LastWriteTimeUtc -gt $stamp) 'A generator source change must regenerate.'
    $stamp = (Get-Item $generated).LastWriteTimeUtc
    $payload = Join-Path $toolDirectory 'bin/Debug/net10.0/ModernFormsNext.WindowKit.Backend.Tools.MicroComGenerator.deps.json'
    (Get-Item $payload).LastWriteTimeUtc = [DateTime]::UtcNow
    Generate
    Assert-Contract ((Get-Item $generated).LastWriteTimeUtc -gt $stamp) 'A runtime input change must regenerate.'
    Assert-Contract ((Get-FileHash $snapshot).Hash -eq $snapshotHash) 'Ordinary generation must not alter the tracked snapshot.'
    Assert-Contract ((Get-FileHash $generated).Hash -eq $snapshotHash) 'Repeated generation must remain deterministic.'

    $design = Invoke-Fixture @('msbuild', $project, '-p:DesignTimeBuild=true', '-getItem:Compile') | ConvertFrom-Json
    Assert-Contract (@($design.Items.Compile).Count -eq 1 -and $design.Items.Compile[0].Identity -like '*MicroCom*Generated.cs') 'IDE evaluation after generation must use the actual generated source.'
    $null = Invoke-Fixture @('msbuild', $project, '-t:UpdateMicroComInteropSnapshot', '-v:q', '/p:UseSharedCompilation=false')
    Assert-Contract ((Get-FileHash $snapshot).Hash -eq $snapshotHash) 'Explicit snapshot refresh must preserve the expected generated bytes.'

    # Generation alone does not execute the normal end-of-build file-write log.
    # Record it explicitly in this fixture, which intentionally never compiles interop.
    $null = Invoke-Fixture @('msbuild', $project, '-t:CollectMicroComGeneratorInputs;_CleanRecordFileWrites', '-v:q', '/p:UseSharedCompilation=false')
    $null = Invoke-Fixture @('clean', $project, '-v:q', '-m:4')
    Assert-Contract (-not (Test-Path $generated)) 'dotnet clean must remove the private generated file.'
    Assert-Contract (Test-Path $snapshot) 'dotnet clean must preserve the tracked IDE snapshot.'
    Write-Host "MicroCom build contracts: $checks assertions passed."
}
finally {
    $resolved = [IO.Path]::GetFullPath($fixture)
    $boundary = [IO.Path]::GetFullPath($parent) + [IO.Path]::DirectorySeparatorChar
    if (-not $resolved.StartsWith($boundary, [StringComparison]::OrdinalIgnoreCase)) { throw 'Unsafe fixture cleanup path.' }
    if (Test-Path -LiteralPath $resolved) { Remove-Item -LiteralPath $resolved -Recurse -Force }
}
