using ModernFormsNext;
using ModernFormsNext.Designer;
using ModernFormsNext.Designer.Services;

namespace ModernFormsNext.DesignerPlayground;

internal sealed class MainForm : Form
{
    private readonly PlaygroundDesignerHostEnvironment hostEnvironment = new();

    public MainForm()
    {
        Text = "ModernFormsNext Designer Playground";
        Name = "DesignerPlayground";
        Size = new System.Drawing.Size(1480, 900);

        var designerShell = new ModernFormsDesignerShell(
            new ModernFormsDesignerOptions
            {
                ShowToolbar = true,
                ShowOutputPanel = true,
                AutoGenerateDesignerCodeOnSave = true
            },
            hostEnvironment);

        designerShell.LoadDocument(DesignerSession.CreateDefaultDocument());
        designerShell.Dock = DockStyle.Fill;

        Controls.Add(designerShell);
    }
}
