<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
	  <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ModernFormsNext.WindowKit\ModernFormsNext.WindowKit.csproj" />
		<ProjectReference Include="..\ModernFormsNext.WindowKit.Backend\ModernFormsNext.WindowKit.Backend.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AvnComIdl Include="..\win32.idl" OutputFile="Generated\Windows.Interop.Generated.cs" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.5" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Generated\" />
  </ItemGroup>

  <Import Project="..\build\MicroCom.targets" />
</Project>
