<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

		<PackageId>ModernFormsNext.WindowKit.Backend.Windows</PackageId>
		<Title>ModernFormsNext WindowKit Windows Backend</Title>
		<Version>$(ModernFormsNextPackageVersion)</Version>
		<Product>ModernFormsNext.WindowKit.Backend.Windows</Product>

		<Description>Windows backend implementation for ModernFormsNext WindowKit.</Description>

		<PackageTags>ui;windowing;desktop;framework;modernforms;windowkit;backend;windows</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\icon.png" Pack="true" PackagePath="\" Link="icon.png" />
		<None Include="..\README.md" Pack="true" PackagePath="\" Link="README.md" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ModernFormsNext.WindowKit.Backend\ModernFormsNext.WindowKit.Backend.csproj" />

		<!-- tymczasowo może zostać -->
		<ProjectReference Include="..\ModernFormsNext.WindowKit\ModernFormsNext.WindowKit.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AvnComIdl Include="..\win32.idl" OutputFile="Generated\Windows.Interop.Generated.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="10.0.10" NoWarn="NU1510" />
		<PackageReference Include="SkiaSharp" Version="3.119.2" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Generated\" />
	</ItemGroup>

	<Import Project="..\build\MicroCom.targets" />

</Project>
