using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using ModernFormsNext;
using ModernFormsNext.Designer.Localization;
using ModernFormsNext.Designer.Services;
using ModernFormsNext.Designer.Surface;

namespace ModernFormsNext.Designer.Layout;

internal sealed class DesignerSettingsDialog : Form
{
    private static readonly IReadOnlyDictionary<DesignerToolWindowId, string> ToolWindowNameKeys =
        new Dictionary<DesignerToolWindowId, string>
        {
            [DesignerToolWindowId.Toolbox] = "Toolbox",
            [DesignerToolWindowId.DocumentOutline] = "DocumentOutline",
            [DesignerToolWindowId.Properties] = "Properties",
            [DesignerToolWindowId.SolutionExplorer] = "SolutionExplorer",
            [DesignerToolWindowId.Output] = "Output"
        };

    private readonly ModernFormsDesignerOptions options;
    private readonly DesignerSession session;
    private readonly ComboBox renderMode;
    private readonly ComboBox language;
    private readonly CheckBox showToolbar;
    private readonly CheckBox showToolboxSearch;
    private readonly CheckBox showDocumentOutlineToolbar;
    private readonly CheckBox showDocumentOutlineSearch;
    private readonly CheckBox autoGenerate;
    private readonly CheckBox autoSave;
    private readonly Dictionary<DesignerToolWindowId, DockRow> dockRows = [];

    public DesignerSettingsDialog(ModernFormsDesignerOptions options, DesignerSession session)
    {
        this.options = options;
        this.session = session;

        Text = T("DesignerSettings");
        Name = "DesignerSettingsDialog";
        Size = new Size(820, 560);
        StartPosition = FormStartPosition.CenterParent;

        Controls.Add(CreateLabel(T("Rendering"), 24, 48, 160));
        renderMode = Controls.Add(new ComboBox
        {
            Left = 190,
            Top = 44,
            Width = 210,
            Height = 26
        });
        renderMode.Items.AddRange(Enum.GetNames<DesignerControlRenderMode>().Cast<object>().ToArray());
        SelectComboValue(renderMode, session.ControlRenderMode.ToString());

        Controls.Add(CreateLabel(T("Language"), 424, 48, 120));
        language = Controls.Add(new ComboBox
        {
            Left = 524,
            Top = 44,
            Width = 160,
            Height = 26
        });
        language.Items.AddRange(Enum.GetNames<DesignerLanguage>().Cast<object>().ToArray());
        SelectComboValue(language, options.Language.ToString());

        showToolbar = Controls.Add(CreateCheckBox(T("ShowToolbar"), 24, 88, options.ShowToolbar));
        autoSave = Controls.Add(CreateCheckBox(T("AutoSave"), 224, 88, options.AutoSaveEnabled));
        autoGenerate = Controls.Add(CreateCheckBox(T("AutoGenerate"), 424, 88, options.AutoGenerateDesignerCodeOnSave));

        showToolboxSearch = Controls.Add(CreateCheckBox(T("ShowToolboxSearch"), 24, 120, options.ShowToolboxSearch));
        showDocumentOutlineToolbar = Controls.Add(CreateCheckBox(T("ShowDocumentOutlineToolbar"), 224, 120, options.ShowDocumentOutlineToolbar));
        showDocumentOutlineSearch = Controls.Add(CreateCheckBox(T("ShowDocumentOutlineSearch"), 424, 120, options.ShowDocumentOutlineSearch));

        Controls.Add(CreateLabel(T("ToolWindows"), 24, 164, 180));
        Controls.Add(CreateHeaderLabel(T("Panel"), 24, 196, 170));
        Controls.Add(CreateHeaderLabel(T("Side"), 204, 196, 130));
        Controls.Add(CreateHeaderLabel(T("Mode"), 344, 196, 130));
        Controls.Add(CreateHeaderLabel(T("Size"), 484, 196, 90));
        Controls.Add(CreateHeaderLabel(T("Order"), 584, 196, 90));

        var rowTop = 226;
        foreach (var id in ToolWindowNameKeys.Keys)
        {
            var row = CreateDockRow(id, rowTop);
            dockRows[id] = row;
            rowTop += 38;
        }

        var ok = Controls.Add(new Button
        {
            Left = 586,
            Top = 484,
            Width = 84,
            Height = 30,
            Text = T("Ok"),
            TextAlign = ContentAlignment.MiddleCenter
        });

        var cancel = Controls.Add(new Button
        {
            Left = 678,
            Top = 484,
            Width = 84,
            Height = 30,
            Text = T("Cancel"),
            TextAlign = ContentAlignment.MiddleCenter
        });

        ok.Click += (_, _) =>
        {
            Apply();
            DialogResult = DialogResult.OK;
        };
        cancel.Click += (_, _) => DialogResult = DialogResult.Cancel;
    }

    private DockRow CreateDockRow(DesignerToolWindowId id, int top)
    {
        var layout = options.GetToolWindowLayout(id);

        Controls.Add(CreateLabel(T(ToolWindowNameKeys[id]), 24, top + 2, 170));

        var side = Controls.Add(new ComboBox
        {
            Left = 204,
            Top = top,
            Width = 130,
            Height = 26
        });
        side.Items.AddRange(Enum.GetNames<DesignerToolWindowSide>().Cast<object>().ToArray());
        SelectComboValue(side, layout.Side.ToString());

        var mode = Controls.Add(new ComboBox
        {
            Left = 344,
            Top = top,
            Width = 130,
            Height = 26
        });
        mode.Items.AddRange(Enum.GetNames<DesignerToolWindowMode>().Cast<object>().ToArray());
        SelectComboValue(mode, layout.Mode.ToString());

        var size = Controls.Add(new NumericUpDown
        {
            Left = 484,
            Top = top,
            Width = 90,
            Height = 28,
            Minimum = 80,
            Maximum = 900,
            Value = Math.Clamp(layout.Size, 80, 900)
        });

        var order = Controls.Add(new NumericUpDown
        {
            Left = 584,
            Top = top,
            Width = 90,
            Height = 28,
            Minimum = 0,
            Maximum = 100,
            Value = Math.Clamp(layout.Order, 0, 100)
        });

        return new DockRow(side, mode, size, order);
    }

    private static Label CreateLabel(string text, int left, int top, int width)
        => new()
        {
            Left = left,
            Top = top,
            Width = width,
            Height = 24,
            Text = text
        };

    private static Label CreateHeaderLabel(string text, int left, int top, int width)
        => new()
        {
            Left = left,
            Top = top,
            Width = width,
            Height = 22,
            Text = text
        };

    private static CheckBox CreateCheckBox(string text, int left, int top, bool isChecked)
        => new()
        {
            Left = left,
            Top = top,
            Width = 260,
            Height = 24,
            Text = text,
            Checked = isChecked
        };

    private static void SelectComboValue(ComboBox comboBox, string value)
    {
        for (var index = 0; index < comboBox.Items.Count; index++)
        {
            if (string.Equals(comboBox.Items[index]?.ToString(), value, StringComparison.Ordinal))
            {
                comboBox.SelectedIndex = index;
                return;
            }
        }

        if (comboBox.Items.Count > 0)
            comboBox.SelectedIndex = 0;
    }

    private void Apply()
    {
        options.ShowToolbar = showToolbar.Checked;
        options.ShowToolboxSearch = showToolboxSearch.Checked;
        options.ShowDocumentOutlineToolbar = showDocumentOutlineToolbar.Checked;
        options.ShowDocumentOutlineSearch = showDocumentOutlineSearch.Checked;
        options.AutoSaveEnabled = autoSave.Checked;
        options.AutoGenerateDesignerCodeOnSave = autoGenerate.Checked;
        if (Enum.TryParse<DesignerLanguage>(language.SelectedItem?.ToString(), out var selectedLanguage))
            options.Language = selectedLanguage;

        foreach (var (id, row) in dockRows)
        {
            var layout = options.GetToolWindowLayout(id);

            if (Enum.TryParse<DesignerToolWindowSide>(row.Side.SelectedItem?.ToString(), out var side))
                layout.Side = side;

            if (Enum.TryParse<DesignerToolWindowMode>(row.Mode.SelectedItem?.ToString(), out var mode))
                layout.Mode = mode;

            layout.Size = Math.Clamp((int)row.Size.Value, 80, 900);
            layout.Order = Math.Clamp((int)row.Order.Value, 0, 100);
        }

        var solutionLayout = options.GetToolWindowLayout(DesignerToolWindowId.SolutionExplorer);
        options.ShowSolutionExplorer = solutionLayout.Mode != DesignerToolWindowMode.Hidden;
        options.SolutionExplorerWidth = solutionLayout.Size;
        options.SolutionExplorerDockMode = solutionLayout.Mode switch
        {
            DesignerToolWindowMode.AutoHide => DesignerDockPanelMode.AutoHide,
            DesignerToolWindowMode.Tabbed => DesignerDockPanelMode.RightTabbed,
            _ => DesignerDockPanelMode.RightSplit
        };

        options.ShowOutputPanel = options.GetToolWindowLayout(DesignerToolWindowId.Output).Mode != DesignerToolWindowMode.Hidden;

        if (Enum.TryParse<DesignerControlRenderMode>(renderMode.SelectedItem?.ToString(), out var render))
        {
            options.InitialControlRenderMode = render;
            session.SetControlRenderMode(render);
        }

        session.NotifySettingsChanged();
        session.Log("Updated designer settings.");
    }

    private string T(string key) => DesignerText.Get(key, options.Language);

    private sealed record DockRow(ComboBox Side, ComboBox Mode, NumericUpDown Size, NumericUpDown Order);
}
