using System.IO;
using System.Linq;
using ModernFormsNext;
using ModernFormsNext.Designer;
using ModernFormsNext.Designer.Services;
using ModernFormsNext.Designing;

namespace ModernFormsNext.VisualStudioDesignerHost;

/// <summary>
/// Hosts the shared ModernFormsNext designer shell in a process launched by the Visual Studio VSIX.
/// </summary>
/// <remarks>
/// Visual Studio packages still load in the .NET Framework in-process extension host. The
/// ModernFormsNext designer and rendering stack target modern .NET, so the VSIX starts this
/// small process and passes the active <c>.mfdesign</c> path instead of duplicating designer UI
/// inside the extension assembly.
/// </remarks>
public sealed class VisualStudioDesignerHostForm : Form
{
    private readonly DesignerHostArguments arguments;
    private readonly VisualStudioDesignerHostEnvironment environment;
    private readonly ModernFormsDesignerShell shell;
    private readonly DesignerHostIpcServer? ipcServer;
    private bool closeConfirmationPending;
    private bool closeConfirmed;

    /// <summary>
    /// Initializes a new instance of the <see cref="VisualStudioDesignerHostForm"/> class.
    /// </summary>
    /// <param name="arguments">The launch arguments supplied by the Visual Studio extension.</param>
    public VisualStudioDesignerHostForm(DesignerHostArguments arguments)
    {
        this.arguments = arguments;

        Text = GetWindowTitle(arguments.DesignDocumentPath);
        Name = "ModernFormsNextVisualStudioDesignerHost";
        Size = new System.Drawing.Size(1480, 900);

        environment = new VisualStudioDesignerHostEnvironment(
            arguments.DesignDocumentPath,
            arguments.ProjectPath ?? FindNearestProjectPath(arguments.DesignDocumentPath));
        shell = new ModernFormsDesignerShell(
            new ModernFormsDesignerOptions
            {
                ShowToolbar = true,
                ShowOutputPanel = true,
                AutoGenerateDesignerCodeOnSave = true
            },
            environment)
        {
            Dock = DockStyle.Fill
        };

        Controls.Add(shell);
        OpenDesignDocument(arguments.DesignDocumentPath, arguments.ProjectPath);

        if (!string.IsNullOrWhiteSpace(arguments.PipeName))
        {
            ipcServer = new DesignerHostIpcServer(
                arguments.PipeName,
                command => Application.RunOnUIThread(() => OpenDesignDocument(command.DesignDocumentPath, command.ProjectPath)));
            ipcServer.Start();
        }

        Closing += HandleClosing;
        Closed += (_, _) => ipcServer?.Dispose();
    }

    protected override void OnKeyDown(KeyEventArgs e)
    {
        if (shell.ProcessDesignerShortcut(e))
            return;

        base.OnKeyDown(e);
    }

    private void HandleClosing(object? sender, System.ComponentModel.CancelEventArgs e)
    {
        if (closeConfirmed)
            return;

        // The windowing close callback is synchronous, while the Designer confirmation can
        // display multiple asynchronous Save/Don't Save/Cancel dialogs. Cancel this attempt and
        // retry only after every document has been confirmed. A second native close request while
        // the prompt is active stays canceled and cannot start a competing confirmation flow.
        e.Cancel = true;
        if (closeConfirmationPending)
            return;

        closeConfirmationPending = true;
        Application.RunOnUIThread(ConfirmCloseAndRetry);
    }

    private async void ConfirmCloseAndRetry()
    {
        try
        {
            if (!await shell.ConfirmCloseAsync(this))
                return;

            closeConfirmed = true;
            Close();
        }
        catch (Exception ex)
        {
            // An exception from an async event continuation must not terminate the host. Keeping
            // the form open also preserves autosave and file monitoring for another close attempt.
            shell.Session.Log($"Could not confirm Designer close: {ex.Message}");
        }
        finally
        {
            closeConfirmationPending = false;
        }
    }

    private void OpenDesignDocument(string? designDocumentPath, string? projectPath)
    {
        Text = GetWindowTitle(designDocumentPath);
        environment.UpdateContext(designDocumentPath, projectPath ?? FindNearestProjectPath(designDocumentPath));

        if (!string.IsNullOrWhiteSpace(designDocumentPath)
            && File.Exists(designDocumentPath))
        {
            try
            {
                shell.Session.OpenDocument(DesignDocumentSerializer.Default.Load(designDocumentPath), designDocumentPath);
                shell.Session.Log($"Opened {designDocumentPath}.");
                return;
            }
            catch (Exception ex)
            {
                shell.Session.Log($"Could not load {designDocumentPath}: {ex.Message}");
            }
        }

        shell.LoadDocument(DesignerSession.CreateDefaultDocument());
    }

    private static string GetWindowTitle(string? designDocumentPath)
        => string.IsNullOrWhiteSpace(designDocumentPath)
            ? "ModernFormsNext Designer"
            : $"{IOPath.GetFileName(designDocumentPath)} [Design] - ModernFormsNext Designer";

    private static string? FindNearestProjectPath(string? path)
    {
        var directory = string.IsNullOrWhiteSpace(path)
            ? null
            : File.Exists(path)
                ? IOPath.GetDirectoryName(path)
                : Directory.Exists(path)
                    ? path
                    : null;

        while (!string.IsNullOrWhiteSpace(directory))
        {
            var project = Directory.EnumerateFiles(directory, "*.csproj").FirstOrDefault();

            if (project is not null)
                return project;

            directory = Directory.GetParent(directory)?.FullName;
        }

        return null;
    }
}
