using System.IO;
using System.Linq;
using ModernFormsNext;
using ModernFormsNext.Designer;
using ModernFormsNext.Designer.Services;
using ModernFormsNext.Designing;

namespace ModernFormsNext.VisualStudioDesignerHost;

/// <summary>
/// Hosts the shared ModernFormsNext designer shell in a process launched by the Visual Studio VSIX.
/// </summary>
/// <remarks>
/// Visual Studio packages still load in the .NET Framework in-process extension host. The
/// ModernFormsNext designer and rendering stack target modern .NET, so the VSIX starts this
/// small process and passes the active <c>.mfdesign</c> path instead of duplicating designer UI
/// inside the extension assembly.
/// </remarks>
public sealed class VisualStudioDesignerHostForm : Form
{
    private readonly DesignerHostArguments arguments;

    /// <summary>
    /// Initializes a new instance of the <see cref="VisualStudioDesignerHostForm"/> class.
    /// </summary>
    /// <param name="arguments">The launch arguments supplied by the Visual Studio extension.</param>
    public VisualStudioDesignerHostForm(DesignerHostArguments arguments)
    {
        this.arguments = arguments;

        Text = GetWindowTitle(arguments.DesignDocumentPath);
        Name = "ModernFormsNextVisualStudioDesignerHost";
        Size = new System.Drawing.Size(1480, 900);

        var environment = new VisualStudioDesignerHostEnvironment(
            arguments.DesignDocumentPath,
            arguments.ProjectPath ?? FindNearestProjectPath(arguments.DesignDocumentPath));
        var shell = new ModernFormsDesignerShell(
            new ModernFormsDesignerOptions
            {
                ShowToolbar = true,
                ShowOutputPanel = true,
                AutoGenerateDesignerCodeOnSave = true
            },
            environment)
        {
            Dock = DockStyle.Fill
        };

        Controls.Add(shell);
        LoadDesignDocument(shell);
    }

    private void LoadDesignDocument(ModernFormsDesignerShell shell)
    {
        if (!string.IsNullOrWhiteSpace(arguments.DesignDocumentPath)
            && File.Exists(arguments.DesignDocumentPath))
        {
            try
            {
                shell.LoadDocument(DesignDocumentSerializer.Default.Load(arguments.DesignDocumentPath));
                shell.Session.Log($"Opened {arguments.DesignDocumentPath}.");
                return;
            }
            catch (Exception ex)
            {
                shell.Session.Log($"Could not load {arguments.DesignDocumentPath}: {ex.Message}");
            }
        }

        shell.LoadDocument(DesignerSession.CreateDefaultDocument());
    }

    private static string GetWindowTitle(string? designDocumentPath)
        => string.IsNullOrWhiteSpace(designDocumentPath)
            ? "ModernFormsNext Designer"
            : $"{Path.GetFileName(designDocumentPath)} [Design] - ModernFormsNext Designer";

    private static string? FindNearestProjectPath(string? path)
    {
        var directory = string.IsNullOrWhiteSpace(path)
            ? null
            : File.Exists(path)
                ? Path.GetDirectoryName(path)
                : Directory.Exists(path)
                    ? path
                    : null;

        while (!string.IsNullOrWhiteSpace(directory))
        {
            var project = Directory.EnumerateFiles(directory, "*.csproj").FirstOrDefault();

            if (project is not null)
                return project;

            directory = Directory.GetParent(directory)?.FullName;
        }

        return null;
    }
}
