using System.Diagnostics;
using System.IO;
using System.Linq;
using ModernFormsNext;
using ModernFormsNext.Designer;
using ModernFormsNext.Designer.Services;
using ModernFormsNext.Designing;

namespace ModernFormsNext.VisualStudioDesignerHost;

/// <summary>
/// Hosts the shared ModernFormsNext designer shell in a process launched by the Visual Studio VSIX.
/// </summary>
/// <remarks>
/// Visual Studio packages still load in the .NET Framework in-process extension host. The
/// ModernFormsNext designer and rendering stack target modern .NET, so the VSIX starts this
/// small process and passes the active <c>.mfdesign</c> path instead of duplicating designer UI
/// inside the extension assembly.
/// </remarks>
public sealed class VisualStudioDesignerHostForm : Form
{
    private readonly DesignerHostArguments arguments;
    private readonly VisualStudioDesignerHostEnvironment environment;
    private readonly ModernFormsDesignerShell shell;
    private readonly DesignerHostIpcServer? ipcServer;
    private readonly WindowsDesignerParentWindowHost? parentWindowHost;
    private Process? ownerProcess;
    private int ownerExitScheduled;
    private bool closeConfirmationPending;
    private bool closeConfirmed;

    /// <summary>
    /// Initializes a new instance of the <see cref="VisualStudioDesignerHostForm"/> class.
    /// </summary>
    /// <param name="arguments">The launch arguments supplied by the Visual Studio extension.</param>
    public VisualStudioDesignerHostForm(DesignerHostArguments arguments)
    {
        this.arguments = arguments;

        Text = GetWindowTitle(arguments.DesignDocumentPath);
        Name = "ModernFormsNextVisualStudioDesignerHost";
        Size = new System.Drawing.Size(1480, 900);

        environment = new VisualStudioDesignerHostEnvironment(
            arguments.DesignDocumentPath,
            arguments.ProjectPath ?? FindNearestProjectPath(arguments.DesignDocumentPath));
        shell = new ModernFormsDesignerShell(
            new ModernFormsDesignerOptions
            {
                ShowToolbar = true,
                ShowOutputPanel = true,
                AutoGenerateDesignerCodeOnSave = true
            },
            environment)
        {
            Dock = DockStyle.Fill
        };

        Controls.Add(shell);
        OpenDesignDocument(arguments.DesignDocumentPath, arguments.ProjectPath);

        if (arguments.ParentWindowHandle != IntPtr.Zero)
            parentWindowHost = new WindowsDesignerParentWindowHost(arguments.ParentWindowHandle);

        if (!string.IsNullOrWhiteSpace(arguments.PipeName))
        {
            ipcServer = new DesignerHostIpcServer(
                arguments.PipeName,
                InvokeIpcCommandAsync);
            ipcServer.Start();
        }

        Closing += HandleClosing;
        Closed += HandleClosed;
    }

    protected override void OnShown(EventArgs e)
    {
        base.OnShown(e);
        if (parentWindowHost is not null)
        {
            parentWindowHost.Attach(this);
            StartOwnerProcessMonitoring(parentWindowHost.OwnerProcessId);
        }
    }

    protected override void OnKeyDown(KeyEventArgs e)
    {
        if (shell.ProcessDesignerShortcut(e))
            return;

        base.OnKeyDown(e);
    }

    private void HandleClosing(object? sender, System.ComponentModel.CancelEventArgs e)
    {
        if (closeConfirmed)
            return;

        // The windowing close callback is synchronous, while the Designer confirmation can
        // display multiple asynchronous Save/Don't Save/Cancel dialogs. Cancel this attempt and
        // retry only after every document has been confirmed. A second native close request while
        // the prompt is active stays canceled and cannot start a competing confirmation flow.
        e.Cancel = true;
        if (closeConfirmationPending)
            return;

        closeConfirmationPending = true;
        Application.RunOnUIThread(ConfirmCloseAndRetry);
    }

    private void StartOwnerProcessMonitoring(int processId)
    {
        Process process;
        try
        {
            process = Process.GetProcessById(processId);
        }
        catch (ArgumentException)
        {
            // The pane HWND was valid during attachment, but Visual Studio can exit between
            // that check and opening its Process object. Treat that race as the normal owner-exit
            // path so the host terminates cleanly instead of surfacing a startup crash.
            HandleOwnerProcessExited(null, EventArgs.Empty);
            return;
        }

        process.EnableRaisingEvents = true;
        process.Exited += HandleOwnerProcessExited;
        ownerProcess = process;
        DesignerHostDiagnosticLog.Write($"Monitoring Visual Studio owner process {processId}.");

        if (process.HasExited)
            HandleOwnerProcessExited(process, EventArgs.Empty);
    }

    private void HandleOwnerProcessExited(object? sender, EventArgs e)
    {
        if (Interlocked.Exchange(ref ownerExitScheduled, 1) != 0)
            return;

        DesignerHostDiagnosticLog.Write("Visual Studio owner process exited; closing owned Designer host.");
        Application.RunOnUIThread(() =>
        {
            closeConfirmed = true;
            Close();
        });
    }

    private void HandleClosed(object? sender, EventArgs e)
    {
        ipcServer?.Dispose();

        if (ownerProcess is not null)
        {
            ownerProcess.Exited -= HandleOwnerProcessExited;
            ownerProcess.Dispose();
            ownerProcess = null;
        }
    }

    private async void ConfirmCloseAndRetry()
    {
        try
        {
            if (!await shell.ConfirmCloseAsync(this))
                return;

            closeConfirmed = true;
            Close();
        }
        catch (Exception ex)
        {
            // An exception from an async event continuation must not terminate the host. Keeping
            // the form open also preserves autosave and file monitoring for another close attempt.
            shell.Session.Log($"Could not confirm Designer close: {ex.Message}");
        }
        finally
        {
            closeConfirmationPending = false;
        }
    }

    private void OpenDesignDocument(string? designDocumentPath, string? projectPath)
    {
        Text = GetWindowTitle(designDocumentPath);
        environment.UpdateContext(designDocumentPath, projectPath ?? FindNearestProjectPath(designDocumentPath));

        if (!string.IsNullOrWhiteSpace(designDocumentPath)
            && File.Exists(designDocumentPath))
        {
            try
            {
                var loadedDocument = DesignDocumentSerializer.Default.Load(designDocumentPath);
                var activeDocument = shell.Session.ActiveOpenDocument;
                if (activeDocument is not null
                    && string.Equals(activeDocument.Path, IOPath.GetFullPath(designDocumentPath), StringComparison.OrdinalIgnoreCase))
                {
                    shell.Session.ReloadDocumentBaseline(
                        activeDocument,
                        loadedDocument,
                        markDirty: false,
                        $"Reloaded {IOPath.GetFileName(designDocumentPath)} from Visual Studio.");
                    shell.Session.Log($"Reloaded {designDocumentPath}.");
                }
                else
                {
                    shell.Session.OpenDocument(loadedDocument, designDocumentPath);
                    shell.Session.Log($"Opened {designDocumentPath}.");
                }

                return;
            }
            catch (Exception ex)
            {
                shell.Session.Log($"Could not load {designDocumentPath}: {ex.Message}");
            }
        }

        shell.LoadDocument(DesignerSession.CreateDefaultDocument());
    }

    private Task<string> InvokeIpcCommandAsync(DesignerHostIpcCommand command)
    {
        var completion = new TaskCompletionSource<string>(TaskCreationOptions.RunContinuationsAsynchronously);
        Application.RunOnUIThread(() =>
        {
            try
            {
                completion.SetResult(HandleIpcCommand(command));
            }
            catch (Exception ex)
            {
                shell.Session.Log($"Visual Studio host command failed: {ex.Message}");
                completion.SetResult("ERROR");
            }
        });
        return completion.Task;
    }

    private string HandleIpcCommand(DesignerHostIpcCommand command)
    {
        switch (command.Kind)
        {
            case DesignerHostIpcCommandKind.Open:
                OpenDesignDocument(command.DesignDocumentPath, command.ProjectPath);
                return "OK";
            case DesignerHostIpcCommandKind.Save:
                return shell.SaveDocument(command.DesignDocumentPath) ? "OK" : "ERROR";
            case DesignerHostIpcCommandKind.QueryDirty:
                return shell.Session.IsDirty ? "DIRTY\t1" : "DIRTY\t0";
            case DesignerHostIpcCommandKind.Shutdown:
                closeConfirmed = true;
                Application.RunOnUIThread(Close);
                return "OK";
            default:
                throw new ArgumentOutOfRangeException(nameof(command), command.Kind, "Unsupported Designer host command.");
        }
    }

    private static string GetWindowTitle(string? designDocumentPath)
        => string.IsNullOrWhiteSpace(designDocumentPath)
            ? "ModernFormsNext Designer"
            : $"{IOPath.GetFileName(designDocumentPath)} [Design] - ModernFormsNext Designer";

    private static string? FindNearestProjectPath(string? path)
    {
        var directory = string.IsNullOrWhiteSpace(path)
            ? null
            : File.Exists(path)
                ? IOPath.GetDirectoryName(path)
                : Directory.Exists(path)
                    ? path
                    : null;

        while (!string.IsNullOrWhiteSpace(directory))
        {
            var project = Directory.EnumerateFiles(directory, "*.csproj").FirstOrDefault();

            if (project is not null)
                return project;

            directory = Directory.GetParent(directory)?.FullName;
        }

        return null;
    }
}
