<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

		<PackageId>ModernFormsNext.WindowKit.Backend</PackageId>
		<Title>ModernFormsNext WindowKit Backend</Title>
		<Version>$(ModernFormsNextPackageVersion)</Version>
		<Product>ModernFormsNext.WindowKit.Backend</Product>

		<Description>Base backend infrastructure for ModernFormsNext WindowKit.</Description>

		<PackageTags>ui;windowing;desktop;framework;modernforms;windowkit;backend</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\icon.png" Pack="true" PackagePath="\" Link="icon.png" />
		<None Include="..\README.md" Pack="true" PackagePath="\" Link="README.md" />
	</ItemGroup>

</Project>
