using System;
using System.Collections.Generic;
using System.Linq;
using ModernFormsNext.Designer.Localization;
using ModernFormsNext.Designer.Surface;
using ModernFormsNext.Designer.Layout;

namespace ModernFormsNext.Designer;

/// <summary>
/// Configures optional UI and command behavior for <see cref="ModernFormsDesignerShell"/>.
/// </summary>
public sealed class ModernFormsDesignerOptions
{
    private readonly Dictionary<DesignerToolWindowId, DesignerToolWindowLayout> toolWindows = CreateDefaultToolWindows();

    /// <summary>
    /// Gets or sets a value indicating whether the designer command toolbar is visible.
    /// </summary>
    public bool ShowToolbar { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether the toolbox search box is visible.
    /// </summary>
    /// <remarks>
    /// Hiding the search box gives more vertical space to the toolbox list while keeping the
    /// same toolbox item model and filtering behavior available for hosts that enable it.
    /// </remarks>
    public bool ShowToolboxSearch { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether the document outline toolbar is visible.
    /// </summary>
    /// <remarks>
    /// The toolbar contains tree display and ordering commands. Hosts can hide it for a more
    /// compact outline while keeping selection and context-menu behavior available.
    /// </remarks>
    public bool ShowDocumentOutlineToolbar { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether the document outline search box is visible.
    /// </summary>
    /// <remarks>
    /// Hiding the search box disables outline filtering in the built-in panel and expands the
    /// visible tree area.
    /// </remarks>
    public bool ShowDocumentOutlineSearch { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether the output/log panel is visible.
    /// </summary>
    public bool ShowOutputPanel { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether designer code should be generated after saving
    /// the <c>.mfdesign</c> document.
    /// </summary>
    public bool AutoGenerateDesignerCodeOnSave { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether dirty Designer documents receive automatic
    /// recovery snapshots.
    /// </summary>
    /// <remarks>
    /// Auto-save writes a separate per-user recovery artifact. It never overwrites the canonical
    /// <c>.mfdesign</c> file, marks the document clean, or changes undo/redo history. Documents
    /// without a path are protected using a temporary document identity and still require Save As.
    /// </remarks>
    public bool AutoSaveEnabled { get; set; } = true;

    /// <summary>
    /// Gets or sets the quiet period after a committed edit before a recovery snapshot is written.
    /// </summary>
    /// <remarks>
    /// The default is two seconds. Repeated committed edits restart this delay, while
    /// <see cref="AutoSaveMaximumInterval"/> remains the upper bound for a dirty document.
    /// Real-time scheduling is coalesced per document and never runs inside an active transaction.
    /// </remarks>
    public TimeSpan AutoSaveDebounceDelay { get; set; } = TimeSpan.FromSeconds(2);

    /// <summary>
    /// Gets or sets the maximum time a dirty document may remain without another recovery attempt.
    /// </summary>
    /// <remarks>
    /// The default is two minutes. This fallback protects long editing sessions whose debounce
    /// timer is repeatedly restarted. A non-positive value disables only the maximum-interval
    /// fallback; committed edits still use <see cref="AutoSaveDebounceDelay"/>.
    /// </remarks>
    public TimeSpan AutoSaveMaximumInterval { get; set; } = TimeSpan.FromMinutes(2);

    /// <summary>
    /// Gets or sets how long inactive Designer recovery artifacts are retained.
    /// </summary>
    /// <remarks>
    /// Cleanup is limited to the dedicated ModernFormsNext recovery directory and never follows
    /// directory links or reparse points. The default retention period is fourteen days.
    /// </remarks>
    public TimeSpan RecoveryRetention { get; set; } = TimeSpan.FromDays(14);

    /// <summary>
    /// Gets or sets the maximum number of inactive recovery artifacts retained for the user.
    /// </summary>
    /// <remarks>
    /// Active documents are excluded from the limit. The default is one hundred artifacts.
    /// Values less than one are treated as one by the recovery cleanup service.
    /// </remarks>
    public int MaximumRecoveryFiles { get; set; } = 100;

    /// <summary>
    /// Gets or sets the language used by designer UI strings.
    /// </summary>
    public DesignerLanguage Language { get; set; } = DesignerLanguage.Auto;

    /// <summary>
    /// Gets or sets the initial rendering mode used by controls on the designer surface.
    /// </summary>
    /// <remarks>
    /// The default value uses the real ModernFormsNext runtime renderers. Placeholder rendering
    /// remains useful when debugging the designer model independently from control renderer bugs.
    /// </remarks>
    public DesignerControlRenderMode InitialControlRenderMode { get; set; } = DesignerControlRenderMode.Runtime;

    /// <summary>
    /// Gets or sets the maximum number of undo units retained for each open Designer document.
    /// </summary>
    /// <remarks>
    /// Removed history units release their retained control subtrees and model values. The value
    /// must be at least one and defaults to 500 entries.
    /// </remarks>
    public int HistoryLimit { get; set; } = 500;

    /// <summary>
    /// Gets or sets a value indicating whether the solution explorer panel is visible.
    /// </summary>
    public bool ShowSolutionExplorer { get; set; } = true;

    /// <summary>
    /// Gets or sets the width, in logical pixels, reserved for the right tool window area.
    /// </summary>
    /// <remarks>
    /// This is the first step toward Visual Studio-like docking. Hosts can persist this value
    /// and feed it back into the shell on the next run.
    /// </remarks>
    public int SolutionExplorerWidth { get; set; } = 330;

    /// <summary>
    /// Gets or sets how the solution explorer panel is placed in the designer shell.
    /// </summary>
    public DesignerDockPanelMode SolutionExplorerDockMode { get; set; } = DesignerDockPanelMode.RightSplit;

    /// <summary>
    /// Gets the configurable tool-window layout map used by the designer shell.
    /// </summary>
    /// <remarks>
    /// The map contains every built-in designer panel. Hosts may mutate these values before
    /// creating the shell or persist them after a settings change.
    /// </remarks>
    public IDictionary<DesignerToolWindowId, DesignerToolWindowLayout> ToolWindows => toolWindows;

    /// <summary>
    /// Gets the layout for the specified tool window, creating a default entry if necessary.
    /// </summary>
    /// <param name="id">The tool-window identifier.</param>
    /// <returns>The mutable layout entry for the requested tool window.</returns>
    public DesignerToolWindowLayout GetToolWindowLayout(DesignerToolWindowId id)
    {
        if (!toolWindows.TryGetValue(id, out var layout))
        {
            layout = CreateDefaultToolWindowLayout(id);
            toolWindows[id] = layout;
        }

        return layout;
    }

    private static Dictionary<DesignerToolWindowId, DesignerToolWindowLayout> CreateDefaultToolWindows()
        => Enum.GetValues<DesignerToolWindowId>()
            .ToDictionary(id => id, CreateDefaultToolWindowLayout);

    private static DesignerToolWindowLayout CreateDefaultToolWindowLayout(DesignerToolWindowId id)
        => id switch
        {
            DesignerToolWindowId.Toolbox => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Left,
                Mode = DesignerToolWindowMode.Docked,
                Size = 260,
                Order = 0
            },
            DesignerToolWindowId.DocumentOutline => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Left,
                Mode = DesignerToolWindowMode.Docked,
                Size = 260,
                Order = 1
            },
            DesignerToolWindowId.Properties => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Right,
                Mode = DesignerToolWindowMode.Docked,
                Size = 330,
                Order = 1
            },
            DesignerToolWindowId.SolutionExplorer => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Right,
                Mode = DesignerToolWindowMode.Docked,
                Size = 330,
                Order = 0
            },
            DesignerToolWindowId.Output => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Bottom,
                Mode = DesignerToolWindowMode.Docked,
                Size = 150,
                Order = 0
            },
            _ => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Right,
                Mode = DesignerToolWindowMode.Docked,
                Size = 300,
                Order = 0
            }
        };
}
