using System;
using System.Collections.Generic;
using System.Linq;
using ModernFormsNext.Designer.Localization;
using ModernFormsNext.Designer.Surface;
using ModernFormsNext.Designer.Layout;

namespace ModernFormsNext.Designer;

/// <summary>
/// Configures optional UI and command behavior for <see cref="ModernFormsDesignerShell"/>.
/// </summary>
public sealed class ModernFormsDesignerOptions
{
    private readonly Dictionary<DesignerToolWindowId, DesignerToolWindowLayout> toolWindows = CreateDefaultToolWindows();

    /// <summary>
    /// Gets or sets a value indicating whether the designer command toolbar is visible.
    /// </summary>
    public bool ShowToolbar { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether the output/log panel is visible.
    /// </summary>
    public bool ShowOutputPanel { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether designer code should be generated after saving
    /// the <c>.mfdesign</c> document.
    /// </summary>
    public bool AutoGenerateDesignerCodeOnSave { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether the active <c>.mfdesign</c> document is saved
    /// automatically whenever the designer model changes.
    /// </summary>
    /// <remarks>
    /// Auto-save only runs when the session has a known document path. Unsaved scratch
    /// documents still require an explicit save command so the designer does not create
    /// unexpected files in the application directory.
    /// </remarks>
    public bool AutoSaveEnabled { get; set; } = true;

    /// <summary>
    /// Gets or sets the language used by designer UI strings.
    /// </summary>
    public DesignerLanguage Language { get; set; } = DesignerLanguage.Auto;

    /// <summary>
    /// Gets or sets the initial rendering mode used by controls on the designer surface.
    /// </summary>
    /// <remarks>
    /// The default value uses the real ModernFormsNext runtime renderers. Placeholder rendering
    /// remains useful when debugging the designer model independently from control renderer bugs.
    /// </remarks>
    public DesignerControlRenderMode InitialControlRenderMode { get; set; } = DesignerControlRenderMode.Runtime;

    /// <summary>
    /// Gets or sets a value indicating whether the solution explorer panel is visible.
    /// </summary>
    public bool ShowSolutionExplorer { get; set; } = true;

    /// <summary>
    /// Gets or sets the width, in logical pixels, reserved for the right tool window area.
    /// </summary>
    /// <remarks>
    /// This is the first step toward Visual Studio-like docking. Hosts can persist this value
    /// and feed it back into the shell on the next run.
    /// </remarks>
    public int SolutionExplorerWidth { get; set; } = 330;

    /// <summary>
    /// Gets or sets how the solution explorer panel is placed in the designer shell.
    /// </summary>
    public DesignerDockPanelMode SolutionExplorerDockMode { get; set; } = DesignerDockPanelMode.RightSplit;

    /// <summary>
    /// Gets the configurable tool-window layout map used by the designer shell.
    /// </summary>
    /// <remarks>
    /// The map contains every built-in designer panel. Hosts may mutate these values before
    /// creating the shell or persist them after a settings change.
    /// </remarks>
    public IDictionary<DesignerToolWindowId, DesignerToolWindowLayout> ToolWindows => toolWindows;

    /// <summary>
    /// Gets the layout for the specified tool window, creating a default entry if necessary.
    /// </summary>
    /// <param name="id">The tool-window identifier.</param>
    /// <returns>The mutable layout entry for the requested tool window.</returns>
    public DesignerToolWindowLayout GetToolWindowLayout(DesignerToolWindowId id)
    {
        if (!toolWindows.TryGetValue(id, out var layout))
        {
            layout = CreateDefaultToolWindowLayout(id);
            toolWindows[id] = layout;
        }

        return layout;
    }

    private static Dictionary<DesignerToolWindowId, DesignerToolWindowLayout> CreateDefaultToolWindows()
        => Enum.GetValues<DesignerToolWindowId>()
            .ToDictionary(id => id, CreateDefaultToolWindowLayout);

    private static DesignerToolWindowLayout CreateDefaultToolWindowLayout(DesignerToolWindowId id)
        => id switch
        {
            DesignerToolWindowId.Toolbox => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Left,
                Mode = DesignerToolWindowMode.Docked,
                Size = 260,
                Order = 0
            },
            DesignerToolWindowId.DocumentOutline => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Left,
                Mode = DesignerToolWindowMode.Docked,
                Size = 260,
                Order = 1
            },
            DesignerToolWindowId.Properties => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Right,
                Mode = DesignerToolWindowMode.Docked,
                Size = 330,
                Order = 1
            },
            DesignerToolWindowId.SolutionExplorer => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Right,
                Mode = DesignerToolWindowMode.Docked,
                Size = 330,
                Order = 0
            },
            DesignerToolWindowId.Output => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Bottom,
                Mode = DesignerToolWindowMode.Docked,
                Size = 150,
                Order = 0
            },
            _ => new DesignerToolWindowLayout
            {
                Side = DesignerToolWindowSide.Right,
                Mode = DesignerToolWindowMode.Docked,
                Size = 300,
                Order = 0
            }
        };
}
